// Integration harness (ticket 2.12).
import * as assert from 'assert';
import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { BinaryState, RedpandaConnect } from '../../adapters/redpandaConnect/binary';
import { BinaryNotifier, MISSING_MESSAGE, NOTIFICATION_ACTIONS } from '../../adapters/redpandaConnect/notify';
import { createVsCodeNotifier, REFRESH_NO_BINARY_LINE, type ExtensionApi } from '../../extension';
import { GapCompletionProvider } from '../../adapters/vscode/completion';
import { SchemaSnapshot, SchemaStore } from '../../adapters/redpandaConnect/schema';
import { schemaFileName } from '../../core/schema';
import {
	connectScript, fixtureBodies, makeTempDir, readCounter, REPO_ROOT, SCHEMA_FIXTURES, toolPath, versionScript, writeFakeBinary,
} from '../helpers/fakeBinary';
import { EXTENSION_ID, waitFor, waitForAsync } from './helpers';

// The fake binary and editor helpers the schema-backed integration suites share (ticket 2.12;
// formerly the 'Schema contributor' suite's own setup). `useSchemaBinary()` registers the suite
// setup and teardown: PATH without a real rpk / redpanda-connect, a fake 4.112.0 binary serving
// the recorded schema fixtures, and a "changed" 4.113.0 binary with one extra input component.

export const EXTRA_INPUT = 'rpcn_test_only_input';

export const api = () => vscode.extensions.getExtension<ExtensionApi>(EXTENSION_ID)!.exports;

let currentDir = '';

/** Waits until `store.current` was generated by `binary` at `version`. */
export async function schemaFrom(binary: string, version: string): Promise<SchemaSnapshot> {
	const store = api().schemaStore;
	assert.ok(await waitFor(() => store.current?.path === binary && store.current.version === version, 30_000),
		`no schema from ${binary} ${version}; current: ${store.current?.path} ${store.current?.version}; `
		+ `binaryState: ${JSON.stringify(api().redpandaConnect.state)}\n${api().outputLines().slice(-10).join('\n')}`);
	return store.current!;
}

export async function setBinaryPath(value: string | undefined): Promise<void> {
	await vscode.workspace.getConfiguration('redpandaConnect').update('binaryPath', value, vscode.ConfigurationTarget.Global);
}

export async function openYaml(name: string, text: string): Promise<vscode.TextDocument> {
	const file = path.join(currentDir, name);
	fs.writeFileSync(file, text);
	const doc = await vscode.workspace.openTextDocument(file);
	await vscode.window.showTextDocument(doc);
	assert.strictEqual(doc.languageId, 'yaml');
	return doc;
}

export async function completionLabels(doc: vscode.TextDocument, position: vscode.Position): Promise<string[]> {
	const list = await vscode.commands.executeCommand<vscode.CompletionList>(
		'vscode.executeCompletionItemProvider', doc.uri, position);
	return (list?.items ?? []).map((item) => (typeof item.label === 'string' ? item.label : item.label.label));
}

export async function hoverText(doc: vscode.TextDocument, position: vscode.Position): Promise<string> {
	const hovers = await vscode.commands.executeCommand<vscode.Hover[]>('vscode.executeHoverProvider', doc.uri, position);
	return (hovers ?? []).flatMap((hv) => hv.contents)
		.map((c) => (typeof c === 'string' ? c : 'value' in c ? c.value : ''))
		.join('\n');
}

/** Polls completion until `expected` labels are all offered (the YAML server may still be starting). */
export async function completionOffers(doc: vscode.TextDocument, position: vscode.Position, expected: string[]): Promise<string[]> {
	let labels: string[] = [];
	const ok = await waitForAsync(async () => {
		labels = await completionLabels(doc, position);
		return expected.every((e) => labels.includes(e));
	}, 45_000);
	assert.ok(ok, `completion did not offer ${expected.join(', ')}; got: ${labels.slice(0, 40).join(', ')}`);
	return labels;
}

export interface SchemaBinary {
	dir: string;
	fakeBinary: string;
	changedBinary: string;
}

/** Call inside a suite: sets up (and tears down) the fake binaries; the fields fill in at suiteSetup. */
export function useSchemaBinary(): SchemaBinary {
	const h: SchemaBinary = { dir: '', fakeBinary: '', changedBinary: '' };
	const originalPath = process.env.PATH;
	suiteSetup(async () => {
		const fixtures = fixtureBodies('4.112.0'); // absolute tool paths: resolved before PATH is filtered
		const cat = toolPath('cat');
		process.env.PATH = (originalPath ?? '').split(path.delimiter)
			.filter((d) => d && !['rpk', 'redpanda-connect'].some((b) => fs.existsSync(path.join(d, b))))
			.join(path.delimiter);
		h.dir = currentDir = makeTempDir('rpcn-contributor-');
		h.fakeBinary = writeFakeBinary(h.dir, 'redpanda-connect', connectScript({ version: '4.112.0', ...fixtures }));

		// A "different binary version": the 4.112.0 schema plus one extra input component.
		const raw = JSON.parse(fs.readFileSync(path.join(SCHEMA_FIXTURES, 'jsonschema-4.112.0.json'), 'utf8'));
		raw.definitions.input.allOf[0].anyOf.push({
			type: 'object',
			properties: { [EXTRA_INPUT]: { type: 'object', additionalProperties: false, properties: {} } },
		});
		const changedSchema = path.join(h.dir, 'jsonschema-changed.json');
		fs.writeFileSync(changedSchema, JSON.stringify(raw));
		h.changedBinary = writeFakeBinary(h.dir, 'redpanda-connect-changed', connectScript({
			version: '4.113.0',
			jsonschema: `'${cat}' '${changedSchema}'`,
			jsonFull: fixtures.jsonFull,
		}));

		await setBinaryPath(h.fakeBinary);
		await schemaFrom(h.fakeBinary, '4.112.0');
		assert.strictEqual(await api().contributorRegistered, true, api().outputLines().join('\n'));
	});
	suiteTeardown(async () => {
		await vscode.commands.executeCommand('workbench.action.closeAllEditors');
		process.env.PATH = originalPath;
		await setBinaryPath(undefined);
		fs.rmSync(h.dir, { recursive: true, force: true });
	});
	return h;
}
